parameters:
  kishlin.app.name: 'rpgidlegame-backend'
  kishlin.app.environment: '%env(APP_ENV)%'
  kishlin.database.url: '%env(DATABASE_URL)%'
  kishlin.src.dir: '/rpgidlegame'
  kishlin.jwt.secretKey: '%env(JWT_SECRET_KEY)%'
  kishlin.jwt.algorithm: '%env(JWT_ALGORITHM)%'
  kishlin.hostname: '%env(HOSTNAME)%'


imports:
  - { resource: ../../../../src/Backend/RPGIdleGame/Shared/Infrastructure/DependencyInjection/Symfony/rpgidlegame_services.yaml }
  - { resource: ../../../../src/Backend/Account/Infrastructure/DependencyInjection/Symfony/account_services.yaml }
  - { resource: ../../../../src/Backend/Shared/Infrastructure/DependencyInjection/Symfony/shared_services.yaml }

services:
  _defaults:
    autoconfigure: true
    autowire: true


###> Errors

  Kishlin\Apps\RPGIdleGame\Backend\Errors\OnKernelException:
    tags:
      - { name: kernel.event_listener, event: kernel.exception }

  Kishlin\Apps\RPGIdleGame\Backend\Errors\ExceptionHandlers\:
    resource: '../src/Errors/ExceptionHandlers'
    tags: ['kishlin.errors.exception-handler']


##> Account

  Kishlin\Apps\RPGIdleGame\Backend\Account\Controller\:
    resource: '../src/Account/Controller'
    tags: ['controller.service_arguments']


##> Monitoring

  Kishlin\Apps\RPGIdleGame\Backend\Monitoring\Controller\:
    resource: '../src/Monitoring/Controller'
    tags: ['controller.service_arguments']
