default:
  suites:
    use_case_tests:
      paths: [ features ]
      contexts:
        - Kishlin\Tests\Backend\UseCaseTests\Context\FightContext
        - Kishlin\Tests\Backend\UseCaseTests\Context\AccountContext
        - Kishlin\Tests\Backend\UseCaseTests\Context\CharacterContext
        - Kishlin\Tests\Backend\UseCaseTests\Context\CharacterCountContext
        - Kishlin\Tests\Backend\UseCaseTests\Context\CharacterStatsContext
    api_tests:
      paths: [ features ]
      contexts:
        - Kishlin\Tests\Apps\RPGIdleGame\Backend\ApiTests\Context\AccountAuthenticationContext
        - Kishlin\Tests\Apps\RPGIdleGame\Backend\ApiTests\Context\AccountSignupContext
        - Kishlin\Tests\Apps\RPGIdleGame\Backend\ApiTests\Context\FightContext
        - Kishlin\Tests\Apps\RPGIdleGame\Backend\ApiTests\Context\FightAccessContext
        - Kishlin\Tests\Apps\RPGIdleGame\Backend\ApiTests\Context\FightFixturesContext
        - Kishlin\Tests\Apps\RPGIdleGame\Backend\ApiTests\Context\CharacterAccessContext
        - Kishlin\Tests\Apps\RPGIdleGame\Backend\ApiTests\Context\CharacterFixturesContext
        - Kishlin\Tests\Apps\RPGIdleGame\Backend\ApiTests\Context\CharacterManagementContext
