imports:
  - { resource: ../../../../CharacterStats/Infrastructure/DependencyInjection/Symfony/character_stats_services.yaml }
  - { resource: ../../../../CharacterCount/Infrastructure/DependencyInjection/Symfony/character_count_services.yaml }
  - { resource: ../../../../Character/Infrastructure/DependencyInjection/Symfony/character_services.yaml }
  - { resource: ../../../../Fight/Infrastructure/DependencyInjection/Symfony/fight_services.yaml }

services:
  _defaults:
    autoconfigure: true
    autowire: true


##> Persistence

  Doctrine\ORM\EntityManagerInterface:
    factory: [ Kishlin\Backend\RPGIdleGame\Shared\Infrastructure\Persistence\Doctrine\EntityManagerFactory\RPGIdleGameEntityManagerFactory, create ]
    arguments:
        $parameters:
          url: '%kishlin.database.url%'
        $environment: '%kishlin.app.environment%'
    public: true

  kishlin.app.infrastructure.entity_manager: '@Doctrine\ORM\EntityManagerInterface'
