nelmio_cors:
  defaults:
    allow_credentials: false
    allow_origin: []
    allow_headers: []
    allow_methods: []
    expose_headers: []
    max_age: 0
    hosts: []
    origin_regex: false
    forced_allow_origin_value: ~
  paths:
    '^/':
      origin_regex: true
      allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
      allow_headers: ['Content-Type', 'Authorization']
      allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
      allow_credentials: true
      max_age: 3600
