services:
  _defaults:
    autoconfigure: true
    autowire: true


  ##> Application

  Kishlin\Backend\Account\Application\Authenticate\AuthenticateCommandHandler:
    class: 'Kishlin\Backend\Account\Application\Authenticate\AuthenticateCommandHandler'
    tags:
      - { name: messenger.message_handler, handles: Kishlin\Backend\Account\Application\Authenticate\AuthenticateCommand }

  Kishlin\Backend\Account\Application\RefreshAuthentication\RefreshAuthenticationCommandHandler:
    class: 'Kishlin\Backend\Account\Application\RefreshAuthentication\RefreshAuthenticationCommandHandler'
    tags:
      - { name: messenger.message_handler, handles: Kishlin\Backend\Account\Application\Authenticate\AuthenticateCommand }

  Kishlin\Backend\Account\Application\Signup\SignupCommandHandler:
    class: 'Kishlin\Backend\Account\Application\Signup\SignupCommandHandler'
    tags:
      - { name: messenger.message_handler, handles: Kishlin\Backend\Account\Application\Signup\SignupCommand }


  ##> Gateways

  Kishlin\Backend\Account\Domain\AccountGateway:
    class: 'Kishlin\Backend\Account\Infrastructure\Persistence\Doctrine\AccountRepository'

  Kishlin\Backend\Account\Domain\AccountReaderGateway:
    class: 'Kishlin\Backend\Account\Infrastructure\Persistence\Doctrine\AccountReaderRepository'

  Kishlin\Backend\Account\Application\Signup\AccountWithEmailGateway:
    class: 'Kishlin\Backend\Account\Infrastructure\Persistence\Doctrine\AccountWithEmailRepository'


  ##> Security

  Kishlin\Backend\Account\Application\Authenticate\AuthenticationGenerator:
    class: 'Kishlin\Backend\Account\Infrastructure\AuthenticationGeneratorUsingFirebase'

  Kishlin\Backend\Account\Application\RefreshAuthentication\SimpleAuthenticationGenerator:
    alias: 'Kishlin\Backend\Account\Application\Authenticate\AuthenticationGenerator'

  Kishlin\Backend\Account\Application\RefreshAuthentication\RefreshTokenParser:
    class: 'Kishlin\Backend\Account\Infrastructure\RefreshTokenParserUsingFirebase'
    bind:
      $secretKey: '%kishlin.jwt.secretKey%'
      $algorithm: '%kishlin.jwt.algorithm%'


  ##> Salt

  Kishlin\Backend\Account\Domain\SaltGenerator:
    class: 'Kishlin\Backend\Account\Infrastructure\SaltGeneratorUsingRandomBytes'
