services:
  _defaults:
    autoconfigure: true
    autowire: true


  ##> Gateways

  Kishlin\Backend\RPGIdleGame\Character\Domain\CharacterGateway:
    class: 'Kishlin\Backend\RPGIdleGame\Character\Infrastructure\Persistence\Doctrine\CharacterRepository'
