services:
  _defaults:
    autoconfigure: true
    autowire: true


  ##> Gateways

  Kishlin\Backend\RPGIdleGame\Character\Domain\CharacterGateway:
    class: 'Kishlin\Backend\RPGIdleGame\Character\Infrastructure\Persistence\Doctrine\CharacterRepository'

  Kishlin\Backend\RPGIdleGame\Character\Domain\CharacterViewGateway:
    class: 'Kishlin\Backend\RPGIdleGame\Character\Infrastructure\Persistence\Doctrine\CharacterViewRepository'

  Kishlin\Backend\RPGIdleGame\Character\Application\CreateCharacter\CreationAllowanceGateway:
    class: 'Kishlin\Backend\RPGIdleGame\Character\Infrastructure\Persistence\Doctrine\CreationAllowanceRepository'

  Kishlin\Backend\RPGIdleGame\Character\Application\DeleteCharacter\DeletionAllowanceGateway:
    class: 'Kishlin\Backend\RPGIdleGame\Character\Infrastructure\Persistence\Doctrine\CreationAllowanceRepository'
